### ISSUE TITLE
'yo alfresco' throws error with node 5.7.1

### ISSUE THREAD

**Issue by vprince1** [binduwavell/generator-alfresco#12] opened 2016-03-04 00:13 UTC
Here is the stacktrace

```
Vijays-MacBook-Pro% yo alfresco
/usr/local/lib/node_modules/generator-alfresco/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/build/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/build/Debug/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/build/Release/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/out/Debug/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/Debug/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/out/Release/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/Release/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/build/default/deasync.node
 → /usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/compiled/5.7.1/darwin/x64/deasync.node
    at bindings (/usr/local/lib/node_modules/generator-alfresco/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-alfresco/node_modules/deasync/index.js:23:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-alfresco/generators/app/dependency-versions.js:2:15)
    at Module._compile (module.js:413:34)
```

To get around this issue you have to install node-gyp using commands

```
npm install -g node-gyp
node-gyp rebuild
```

**Comment by binduwavell** [comment] 2016-03-04 00:27
Vijay and I worked on this together. Once we fully uninstalled generator alfresco and reinstalled it, worked perfectly and included the binding file we had to generate previously. Strangely it was working earlier today and somehow the binary for deasync for mac and node5 was simply missing, all other binaries for deasync were there. I made sure to have the same version of node, same version of xcode, etc and I can't reproduce. I'm closing this as cannot reproduce, but big thanks to Vijay for documenting how to work around this if others run into it.

You should be able to `npm rm -g generator-alfresco` and then `npm install -g binduwavell/generator-alfresco` as an alternative to using node-gyp.

**Closed as completed** 2016-03-04 00:27 UTC
Labels: wontfix
